baseURL = 'https://harshmishra2991.github.io/'
languageCode = 'en-us'
title = 'Harsh Mishra'
theme = 'PaperMod'

enableRobotsTXT = true


[params]
description = "Product, investing, systems thinking"
author = "Harsh Mishra"
defaultTheme = "light"
ShowReadingTime = true
ShowShareButtons = false

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/harsh-mishra-722675128/"

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1


[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "PMing"
url = "/categories/pming/"
weight = 3

[[menu.main]]
name = "Wiki"
url = "/wiki/"
weight = 4

